### ISSUE TITLE
Criação de cadastro de estabelecimento

### ISSUE THREAD

**Issue by luizvnasc** [CodeForCuritiba/coronga-tracker#2]
A aplicação deverá ter um cadastro de estabelecimentos que os donos que desejam participar dos rastreio e então poder obter os templates do qrcode para colocar  em seu estabelecimento.

### Sugestão  de informações do cadastro:
* CNPJ
* Endereço (rua, bairro, cidade, estado, cep)
* Senha

**Comment by ricardomendesjr** [comment]
Acrescentar:
Nome do estabelecimento
Nome e telefone do responsável

**Comment by Abreums** [comment]
Não será necessário o cadastro. 
Os estabelecimentos poderão fazer o mesmo acompanhamento de risco de exposição que um usuário normal. Isto poderá ser obtido tanto desde dispositivos móveis, quanto de um desktop, desde que o usuário tenha o registro de localização do estabelecimento.

**Comment by Abreums** [comment]
Com a solução proposta esta issue será fechada. 
Após MVP uma eventual reavaliação poderá ser feita.
