### ISSUE TITLE
Criação de cadastro de usuário

### ISSUE THREAD

**Issue by luizvnasc** [CodeForCuritiba/coronga-tracker#3]
a aplicação deverá ter um cadastro dos usuários que gostariam de participar do rastreio.

### Sugestão de informações do cadastro
* CPF
* N° telefone
* senha
* opção de vinculação com login de redes sociais

**Comment by ricardomendesjr** [comment]
De acordo. talvez obrigar a usar o login do Android? não sei como é no iOS

**Comment by Abreums** [comment]
Não é necessário cadastro de usuários. 
O sistema operará apenas com administrador. 
A validação dos dados será feita automaticamente cruzando os dados compartilhados com a base da Secretaria da Saúde. Caso a base da Secretaria de Saúde não seja disponibilizada, esta issue deverá ser revista.
