### ISSUE TITLE
Serviço de checkin

### ISSUE THREAD

**Issue by luizvnasc** [CodeForCuritiba/coronga-tracker#4]
A aplicação deverá ter uma url para cada estabelecimento onde o usuário irá ser direcionado para um check-in de que esteve naquele estabelecimento, o checkin deverá conter:

* ID/CNPJ  do estabelecimento
* ID/CPF do usuário
* data de checkin

**Comment by ricardomendesjr** [comment]
Caso de uso:
**Fazer o check-in**
1. [IN] O usuário aponta a câmera do smartphone para o QR Code do estabelecimento
2. [OUT] O sistema abre a página de confirmação do check-in
3. [IN] O usuário confirma o check-in
4. [OUT] Sistema confirma check-in e registra Estabelecimento na Lista do Usuário

**Exceção 1a: Estabelecimento não cadastrado**
1a. 1. [IN] Responsável faz login social
1a. 2. [IN] Responsável informa nome do estabelecimento, nome do responsável, endereço e telefone
1a. 3. [IN] Responsável gera QR Code

**Exceção 1b: Usuário não cadastrado**
1b. 1. [IN] Usuário faz login social
1b. 2. [IN] Usuário informa CPF e telefone

**Exceção 1c: Estabelecimento não tem QR Code**
1c. 1. [IN] Responsável faz o login social
1c. 2. [IN] Responsável seleciona gerar QR Code

**Comment by Abreums** [comment]
Não será preciso checkin. No MVP vamos trabalhar com os dados do GPS do dispositivo.
