### ISSUE TITLE
Serviço para listar possíveis contatos entre pessoas com pessoa infectada

### ISSUE THREAD

**Issue by luizvnasc** [CodeForCuritiba/coronga-tracker#5]
A aplicação deverá ter um serviço onde dado um cpf, o sistema liste todos os possíveis contatos entre esta pessoa e pessoas que estiveram no mesmo estabelecimento que ela.

**Comment by ricardomendesjr** [comment]
Eu não entendi porque você abriu uma issue para cada feature. o que temos que discutir ou estender aqui. abri uma issue com a descrição geral do sistema. aguardo instruções.

**Comment by ricardomendesjr** [comment]
sim, esse é o objetivo principal do aplicativo. detalhei desta forma:
Se o usuário por algum motivo procurar uma unidade de saúde, ou realizar o teste do Covid numa farmácia ou laboratório a secretaria de saúde será informada. Um servidor da secretaria de saúde irá acessar o sistema, localizar este usuário pelo CPF e identificar todos os estabelecimentos que esse usuário fez check-in nos últimos 14 dias, com as informações de data e hora. Irá também listar todos os usuários que estiveram nos mesmos estabelecimentos no intervalo de 30 minutos após o check-in do usuário. Com a lista, irá verificar se estes usuários já tiveram algum contato com a secretaria e em caso negativo irá fazer contato telefônico com cada um para verificar o seu estado de saúde.

Precisaria definir o intervalo de tempo na busca dos contatos no mesmo estabelecimento e o intervalo de dias na busca dos estabelecimentos da pessoa. Pode-se definir um padrão e deixar o servidor modificar na busca

**Comment by ricardomendesjr** [comment]
Caso de uso:
**Consultar usuário**
1. [IN] Servidor faz login social
2. [IN] Servidor informa CPF do Usuário
3. [OUT] Sistema informa estabelecimentos em que o usuário fez check-in com nome, endereço, data e hora
4. [IN] Servidor seleciona check-in
5. [OUT] Sistema informa todos os Usuários com check-in no intervalo de 30 minutos após o check-in com CPF e telefone

**Exceção 1a: Servidor não cadastrado**
1a. 1. Servidor faz login social
1a. 2. Servidor informa nome, matrícula e telefone

**Comment by Abreums** [comment]
nope
