### ISSUE TITLE
Visão geral do sistema

### ISSUE THREAD

**Issue by ricardomendesjr** [CodeForCuritiba/coronga-tracker#6]
Covid tracker: desenvolver um sistema para realizar o check-in do usuário para entrar em um estabelecimento comercial. 
Para isso, são registrados os estabelecimentos comerciais e seus clientes. Os clientes são os usuários do sistema. 
Para usar o sistema o estabelecimento comercial faz um cadastro, com CNPJ, nome fantasia, endereço e telefone para contato.
O estabelecimento deve indicar um responsável - o proprietário ou gerente, para contato da Prefeitura se necessário. 
Para cada usuário, é necessário cadastrar o seu CPF, informações de login e número do celular.
Quando um usuário entrar em um estabelecimento, o responsável irá fazer o check-in do usuário, sendo registrados a data e a hora.
Opcionalmente o estabelecimento poderá fazer agendamentos de clientes no sistema, buscando o usuário pelo CPF e informando
a data e horário.
Se o usuário por algum motivo procurar uma unidade de saúde, ou realizar o teste do Covid numa farmácia ou laboratório a 
secretaria de saúde será informada. A secretaria de saúde irá acessar o sistema, localizar este usuário pelo CPF e identificar
todos os estabelecimentos que esse usuário fez check-in nos últimos 14 dias, com as informações de data e hora. 
Irá também listar todos os usuários que estiveram nos mesmos estabelecimentos no intervalo de 30 minutos após o check-in do
usuário. Com a lista, irá verificar se estes usuários já tiveram algum contato com a secretaria e em caso negativo irá fazer contato
telefônico com cada um para verificar o seu estado de saúde.

**Comment by ricardomendesjr** [comment]
Entidades (ou conceitos) do sistema
Check-in: ação de ler o QR Code e registrar a entrada no estabelecimento
Estabelecimento: qualquer estabelecimento que tenha entrada de pessoas
Responsável: pessoa responsável pelo estabelecimento e que possa ser contatada pela secretaria
Agendamento: ação do usuário em agendar horário para ir ao estabelecimento. deve ser validada pelo Responsável
Usuário: pessoa que faz o check-in
Servidor: funcionário da secretaria de saúde que faz a consulta

**Comment by ricardomendesjr** [comment]
Acrescentei o Agendamento, pois vi que em algumas cidades está sendo obrigatório agendar o serviço, como em salões de beleza e academias. Na Europa (não sei se em todos os países) os turistas terão que agendar todas as visitas que irão fazer na cidade. É o novo norma!

**Comment by Abreums** [comment]
Visão geral foi transferida para READ.ME do repositório.
