### ISSUE TITLE
Conceitos (Classe) e atributos

### ISSUE THREAD

**Issue by ricardomendesjr** [CodeForCuritiba/coronga-tracker#9]
**Estabelecimento**
<<único>> CNPJ
nome_fantasia
rua
número
complemento
Cep
cidade
telefone_ddd
telefone_numero
responsável

**Usuário**
<<único>> CPF
telefone_ddd
Telefone_numero
cidade

**Check-in**
<<único>> id
data
hora

**Agendamento**
<<único>> id
data
Hora

**Servidor**
<<único>> matrícula
nome
telefone_dd
telefone_numero
cidade

**Lista de estabelecimentos do Usuário**
<<único>> id
CNPJ

**Comment by Abreums** [comment]
nope
